---
title: "Simul_function"
author: "Enzo Moraes Mescall"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(tidyverse)
library(invgamma)
library(fitdistrplus)
```

```{r}
data_23 = read.csv("Cleaned Data/modified_2023.csv") %>%
  mutate(Apparatus = toupper(Apparatus))
data_21 = read.csv("Cleaned Data/data_2017_2021.csv") 
```


```{r}
analyze_athlete = function(athlete_results, m_0, sig_0, k_0, v_0, smc = 1000) {
  n = length(athlete_results)
  ybar = mean(athlete_results)
  
  if (is.na(var(athlete_results))) {
    var = 0
  } else {
    var = var(athlete_results) 
  }
  
  k_n = k_0 + n
  v_n = v_0 + n
  m_n = (k_0*m_0 + n*ybar)/k_n
  sig_n = (v_0*sig_0 + (n-1)*var + k_0*n*(ybar - m_0)**2/k_n)/v_n
  sig_sample = mean(rinvgamma(smc, v_n/2, sig_n*v_n/2))
  theta_sample = mean(rnorm(smc, m_n, sqrt(sig_sample/k_n)))
  
  return(c(theta_sample, sig_sample))
}
```


```{r}
fit_normal_priors = function(data, apparatus, gender) {
  prior_info = data %>%
    filter(Apparatus == apparatus,
           Gender == gender) %>%
    group_by(FirstName, LastName, Country) %>%
    summarise(mean_score = mean(Score),
              var_score = var(Score))  %>%
    mutate(var_score = ifelse(is.na(var_score), 0, var_score))
  
  normal_mu_fit = fitdist(prior_info$mean_score, "norm")

  invgamma_sd_fit = fitdist(prior_info$var_score[prior_info$var_score > 0], "invgamma")
  
  m_0 =  normal_mu_fit$estimate[[1]]
  sig_0 = normal_mu_fit$estimate[[2]]
  k_0 = invgamma_sd_fit$estimate[[1]] 
  v_0 = invgamma_sd_fit$estimate[[2]]

  return(c(m_0 = m_0, sig_0 = sig_0, k_0 = k_0, v_0 = v_0))
}
```

```{r}
analyze_athlete = function(athlete_results, m_0, sig_0, k_0, v_0) {
  n = length(athlete_results)
  ybar = mean(athlete_results)
  
  if (is.na(var(athlete_results))) {
    var = 0
  } else {
    var = var(athlete_results) 
  }
  
  # If somebody could verify this Bayesian 
  k_n = k_0 + n
  v_n = v_0 + n
  m_n = (k_0*m_0 + n*ybar)/k_n
  sig_n = (v_0*sig_0 + (n-1)*var + k_0*n*(ybar - m_0)**2/k_n)/v_n
  sig_sample = rinvgamma(1, v_n/2, sig_n*v_n/2)
  theta_sample = rnorm(1, m_n, sqrt(sig_sample/k_n))
  
  return(c(theta_sample, sig_sample))
}
```


```{r}
# So this represents one simulation, we could probably run this like 1000 times and average out the medal counts
simulate_results = function(data, apparatus, gender, m_0, sig_0, k_0, v_0, medals = TRUE) {
  simul_data = data %>%
    filter(Apparatus == apparatus
           , Gender == gender) %>%
    group_by(FirstName, LastName, Country) %>%
    summarise(mean_estimate = analyze_athlete(Score, m_0 = m_0, sig_0 = sig_0, k_0 = k_0, v_0 = v_0)[1],
              var_estimate = analyze_athlete(Score, m_0 = m_0, sig_0 = sig_0, k_0 = k_0, v_0 = v_0)[2], .groups = "keep") %>%
    rowwise() %>%
    mutate(simulated_Score = rnorm(1, mean_estimate, var_estimate)) %>% # Truncate scores > 10
    #mutate(simulated_Score = ifelse(simulated_Score > 20, 10, simulated_Score)) %>% # Truncate scores < 0
    #mutate(simulated_Score = ifelse(simulated_Score < 0, 0, simulated_Score)) %>% Ignoring truncation since if somebody gets a 20 they'll get the medal anyways
    ungroup() %>%
    arrange(desc(simulated_Score)) %>% # assign medals
    mutate(medal = case_when(row_number() == 1 ~ "Gold",
                             row_number() == 2 ~ "Silver",
                             row_number() == 3 ~ "Bronze", 
                             TRUE ~ "NA"))
  return(simul_data)
}
```

```{r}  
# full competition simulation, gets pretty slow with 1000 simulations
simulate_full_competition = function(data, apparatus, gender, mu_0, sig_0, k_0, v_0, smc = 1) {
  athletes_medals = data %>%
    dplyr::select(FirstName, LastName, Country) %>%
    distinct() %>%
    mutate(Golds = 0, Silvers = 0, Bronzes = 0, Total_Medals = 0)
  
  print("Starting Simulation")
  for (i in 1:smc) {    
    big_simul = simulate_results(data, apparatus, gender, mu_0, sig_0, k_0, v_0, TRUE) %>%
      filter(medal != "NA") %>%
      group_by(FirstName, LastName, Country) %>%
      summarise(Golds = sum(medal == "Gold"),
                Silvers = sum(medal == "Silver"),
                Bronzes = sum(medal == "Bronze"),
                Total_Medals = sum(medal != "NA"),
                .groups = "keep") %>%
      ungroup()
    
    athletes_medals = athletes_medals %>%
      left_join(big_simul, by = c("FirstName", "LastName", "Country")) %>%
      mutate(Golds = ifelse(is.na(Golds.y), Golds.x, Golds.y + Golds.x),
             Silvers = ifelse(is.na(Silvers.y), Silvers.x, Silvers.y + Silvers.x),
             Bronzes = ifelse(is.na(Bronzes.y), Bronzes.x, Bronzes.y + Bronzes.x),
             Total_Medals = ifelse(is.na(Total_Medals.y), Total_Medals.x, Total_Medals.y + Total_Medals.x)) %>%
      dplyr::select(FirstName, LastName, Country, Golds, Silvers, Bronzes, Total_Medals) %>%
      arrange(desc(Total_Medals))
  } 
  return(athletes_medals)
}
```

```{r}
# This is how it sort of would work
prior_parameters = suppressWarnings(fit_normal_priors(data_23, "FX", "w"))
print(prior_parameters)

mu_0 = prior_parameters[1]
sig_0 = prior_parameters[2]
k_0 = prior_parameters[3]
v_0 = prior_parameters[4]

test_simul = simulate_full_competition(data_23, "FX", "w", mu_0, sig_0, k_0, v_0, 1000)
head(test_simul)
```



